image: eguerin/antlr4cpp

build:
    stage: build
    script:
        - cd SqueletteProjet/compiler
        - make ANTLR4_INCDIR=/usr/include/antlr4-runtime ANTLR4_BINDIR=/bin ANTLR4_LIBDIR=/lib/x86_64-linux-gnu
    artifacts:
        paths:
            - SqueletteProjet/compiler/ifcc
        name: artifact:build
        when: on_success
        expire_in: 1 weeks

test:
    stage: test
    dependencies:
        - build
    script:
        - chmod 755 SqueletteProjet/compiler/ifcc
        - cd SqueletteProjet/tests/
        - chmod 755 pld-wrapper.sh
        - python3 pld-test.py tests/Init/
    artifacts:
        paths:
            - SqueletteProjet/tests/pld-test-output
        name: artifact:test
        when: on_success
        expire_in: 1 weeks
